/**
 * Host-local Worker state for the macOS CLI (#117, ADR-0003/0012).
 *
 * The `sprout worker` command owns three kinds of host-local fact and nothing
 * else:
 *
 * - the **configuration** needed to reconnect (endpoint, enrollment id,
 *   environment instance, protocol version) — never a browser credential, an
 *   engine credential, a hostname inventory, or an absolute workspace path;
 * - the **identity key** generated on this host, stored owner-only, which never
 *   crosses the core boundary and never appears in argv, output, or a log; and
 * - the **runtime state** that lets `status` tell a stopped Worker from a
 *   connecting, connected, incompatible, or revoked one without reading a
 *   secret.
 *
 * Everything here is deliberately a filesystem seam: the paths, the restrictive
 * permissions, and the parse/validate rules live in one Module so the commands,
 * the `status` projection, and the tests cannot disagree about what "host-local
 * restrictive storage" means.
 */

import { createHash, randomBytes } from 'node:crypto';
import {
  chmodSync,
  closeSync,
  existsSync,
  fsyncSync,
  lstatSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmdirSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { execFileSync } from 'node:child_process';

import {
  PRIVATE_DIRECTORY_MODE,
  PRIVATE_FILE_MODE,
  writePrivateFile,
} from '../host-files.ts';
import { WORKER_DIAGNOSTICS } from '../diagnostics.ts';
import { validateWorkerIdentityPrivateKey } from '../../environment/worker-proof.ts';

/** The LaunchAgent label prefix the Worker service uses on macOS. */
export const WORKER_SERVICE_LABEL_PREFIX = 'dev.sprout.worker';

/** The private key file name inside the state directory. */
export const WORKER_IDENTITY_FILE = 'identity.pem';

export { PRIVATE_FILE_MODE, PRIVATE_DIRECTORY_MODE };

/**
 * The connection facts the Worker persists to reconnect.
 *
 * This is deliberately the *minimum*: the endpoint it dials, the enrollment that
 * authorizes it, the environment instance it serves, and the Worker protocol
 * version. There is no field for a Human browser credential, an engine
 * credential, a hostname inventory, or an absolute workspace path, so none can
 * be persisted by accident.
 */
export interface WorkerHostConfig {
  readonly version: 1;
  readonly enrollmentId: string;
  readonly environmentInstanceId: string;
  readonly protocolVersion: string;
  readonly endpoint: { readonly host: string; readonly port: number };
  /** The private key file name, resolved relative to the state directory. */
  readonly identityFileName: string;
}

/** The connection states a Worker's `status` distinguishes. */
export type WorkerConnectionState =
  | 'stopped'
  | 'connecting'
  | 'connected'
  | 'pending-approval'
  | 'incompatible'
  | 'revoked';

/**
 * The live daemon's own record of what it is doing.
 *
 * It is written by `start` and read by `status`; it carries no secret and no
 * free-form endpoint text. The pid plus process identity is what lets `status`
 * ignore a stale file whose pid the OS has since reused.
 */
export interface WorkerRuntimeState {
  readonly pid: number;
  /**
   * The opaque binding of this record to one OS process incarnation.  It is
   * host-local, owner-only metadata, never command-line text or portable state.
   */
  readonly process: WorkerProcessIdentity;
  readonly state: WorkerConnectionState;
  /** The instant the state was last observed, in epoch milliseconds. */
  readonly at: number;
  /** An optional, already-sanitized explanation suitable for an operator. */
  readonly detail?: string;
  /** The Worker connection epoch, when the core has accepted one. */
  readonly epoch?: number;
}

/**
 * Evidence that one particular local process owns Worker state.
 *
 * `ownerToken` is freshly generated by `start` and inherited only in that
 * process environment. `startIdentity` is the OS's process-start marker.  The
 * pair prevents a PID reused by another process (or another environment's
 * Worker) from inheriting authority over runtime or lock files.
 */
export interface WorkerProcessIdentity {
  readonly pid: number;
  readonly startIdentity: string;
  readonly ownerToken: string;
}

/**
 * The result of probing a local process binding.
 *
 * `dead` is positive proof that the pid is gone. `alive` contains enough
 * evidence to compare the exact process incarnation. `unknown` means the pid
 * may still be alive, but the platform or permissions could not expose the
 * owner token or start marker. It is deliberately distinct from `dead`: lock
 * reclamation must never turn unavailable evidence into permission to start a
 * second Worker or to destroy its host state.
 */
export type WorkerProcessProbeResult =
  | { readonly state: 'dead' }
  | { readonly state: 'alive'; readonly process: WorkerProcessIdentity }
  | { readonly state: 'unknown' };

/** Probe the small, comparable process facts needed for host-local ownership. */
export type WorkerProcessProbe = (pid: number) => WorkerProcessProbeResult;

/** Why the host-local Worker state could not be used. */
export class WorkerHostStateError extends Error {
  override readonly name = 'WorkerHostStateError';
  /** `not-enrolled` is distinct from `invalid` so the CLI can exit differently. */
  readonly reason: 'not-enrolled' | 'invalid';

  constructor(reason: 'not-enrolled' | 'invalid', message: string) {
    super(message);
    this.reason = reason;
  }
}

export interface WorkerHostPaths {
  /** The owner-only directory holding config, identity, and runtime state. */
  readonly stateDirectory: string;
  readonly configPath: string;
  readonly identityPath: string;
  readonly runtimePath: string;
  readonly logPath: string;
  /** The directory LaunchAgents are written to. */
  readonly launchAgentsDirectory: string;
  /** The absolute path of the `sprout` executable this process was started by. */
  readonly executablePath: string;
  /** The Node executable that runs the TypeScript sources. */
  readonly nodeExecutable: string;
}

/**
 * Resolve every host-local path once.
 *
 * The defaults are the signed-in user's own directories, so a Worker runs in
 * their login context (ADR-0009). Tests and the independent probes override the
 * directory roots through the environment rather than through arguments, so no
 * command line ever has to carry a host path.
 */
export function workerHostPaths(environment: NodeJS.ProcessEnv = process.env): WorkerHostPaths {
  const home = environment['HOME'] ?? homedir();
  const stateDirectory = environment['SPROUT_WORKER_HOME'] ?? join(home, '.sprout', 'worker');
  const launchAgentsDirectory =
    environment['SPROUT_LAUNCH_AGENTS_DIR'] ?? join(home, 'Library', 'LaunchAgents');
  return {
    stateDirectory,
    configPath: join(stateDirectory, 'config.json'),
    identityPath: join(stateDirectory, WORKER_IDENTITY_FILE),
    runtimePath: join(stateDirectory, 'runtime.json'),
    logPath: join(stateDirectory, 'worker.log'),
    launchAgentsDirectory,
    executablePath: environment['SPROUT_CLI_PATH'] ?? defaultExecutablePath(),
    nodeExecutable: process.execPath,
  };
}

/**
 * The `sprout` entry point this process is running from.
 *
 * The CLI sets `SPROUT_CLI_PATH` when it dispatches so the rendered LaunchAgent
 * names the same executable the operator invoked; this fallback keeps a directly
 * imported Module honest without guessing a repository layout.
 */
function defaultExecutablePath(): string {
  return process.argv[1] ?? process.argv[0] ?? 'sprout';
}

/** The LaunchAgent label for one environment instance. */
export function workerServiceLabel(environmentInstanceId: string): string {
  return `${WORKER_SERVICE_LABEL_PREFIX}.${stableSlug(environmentInstanceId)}`;
}

/**
 * A filesystem-safe, collision-resistant slug.
 *
 * It is a one-way SHA-256 digest of the value, hex-encoded: a label or plist
 * path never contains any fragment of the caller-chosen instance name, so no
 * host-chosen text can leak into host-local service metadata. It is stable so
 * install/uninstall/inspect agree, and 16 hex characters (64 bits) make a
 * cross-environment collision negligible for the small number of enrolled
 * instances one host manages.
 */
export function stableSlug(value: string): string {
  return createHash('sha256').update(value, 'utf8').digest('hex').slice(0, 16);
}

/** Ensure the owner-only state directory exists. */
export function ensureStateDirectory(paths: WorkerHostPaths): void {
  mkdirSync(paths.stateDirectory, { recursive: true, mode: PRIVATE_DIRECTORY_MODE });
  // `mkdir` respects the mode only on creation; an existing directory is left as
  // the operator made it, so tighten it explicitly.
  chmodSync(paths.stateDirectory, PRIVATE_DIRECTORY_MODE);
}

/** Whether a file's mode grants no group or world access. */
export function isRestrictive(filePath: string): boolean {
  const mode = statSync(filePath).mode & 0o777;
  return (mode & 0o077) === 0;
}

/** Whether a private identity file has exactly the mode we create (0600). */
export function hasExactPrivateFileMode(filePath: string): boolean {
  return (statSync(filePath).mode & 0o777) === PRIVATE_FILE_MODE;
}

export { writePrivateFile };

/** Remove a file if it exists, ignoring an already-absent one. */
export function removeFileIfPresent(filePath: string): void {
  try {
    unlinkSync(filePath);
  } catch {
    // A missing file is the desired end state.
  }
}

/**
 * Remove a file, tolerating only its absence.
 *
 * `reset` must fail closed: a removal error that is silently swallowed could
 * leave the old identity key behind while the command reports success.
 */
function removeFileRequired(filePath: string): void {
  try {
    unlinkSync(filePath);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
}

/** Read and validate the identity private key, refusing unsafe or malformed material. */
export function readIdentityKey(paths: WorkerHostPaths): string {
  try {
    const stat = lstatSync(paths.identityPath);
    if (!stat.isFile()) throw new Error('not a regular file');
    if ((stat.mode & 0o777) !== PRIVATE_FILE_MODE) {
      throw new Error('invalid permissions');
    }
    const privateKey = readFileSync(paths.identityPath, 'utf8');
    validateWorkerIdentityPrivateKey(privateKey);
    return privateKey;
  } catch (error) {
    if (error instanceof WorkerHostStateError) throw error;
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      throw new WorkerHostStateError('invalid', 'the host-local Worker identity key is missing');
    }
    if (error instanceof Error && error.message === 'the host-local Worker identity key is not a valid Ed25519 private key') {
      throw new WorkerHostStateError('invalid', error.message);
    }
    throw new WorkerHostStateError(
      'invalid',
      'the host-local Worker identity key is unreadable, malformed, or does not have the required owner-only permissions; run reset and enroll again',
    );
  }
}

/** Whether a host-local enrollment already exists. */
export function isEnrolled(paths: WorkerHostPaths): boolean {
  return existsSync(paths.configPath);
}

/**
 * Load the persisted configuration, validating that it is structurally sound.
 *
 * A corrupt document is a *local configuration failure* rather than a silent
 * re-enrollment, because rotating the identity would orphan the core-side
 * binding the operator already approved.
 */
export function readConfig(paths: WorkerHostPaths): WorkerHostConfig {
  if (!existsSync(paths.configPath)) {
    throw new WorkerHostStateError('not-enrolled', 'this host has no Sprout Worker enrollment');
  }
  if (!isRestrictive(paths.configPath)) {
    throw new WorkerHostStateError(
      'invalid',
      'the host-local Worker configuration is readable by other users; run reset and enroll again',
    );
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(paths.configPath, 'utf8'));
  } catch {
    throw new WorkerHostStateError('invalid', 'the host-local Worker configuration is not valid JSON');
  }
  return validateConfig(parsed);
}

/** Validate a parsed configuration without echoing any of its values. */
export function validateConfig(parsed: unknown): WorkerHostConfig {
  if (typeof parsed !== 'object' || parsed === null) {
    throw new WorkerHostStateError('invalid', 'the host-local Worker configuration is not an object');
  }
  const record = parsed as Record<string, unknown>;
  const endpoint = record['endpoint'];
  const host = typeof endpoint === 'object' && endpoint !== null ? (endpoint as Record<string, unknown>)['host'] : undefined;
  const port = typeof endpoint === 'object' && endpoint !== null ? (endpoint as Record<string, unknown>)['port'] : undefined;
  const enrollmentId = record['enrollmentId'];
  const environmentInstanceId = record['environmentInstanceId'];
  const protocolVersion = record['protocolVersion'];
  const identityFileName = record['identityFileName'];
  if (
    record['version'] !== 1 ||
    typeof enrollmentId !== 'string' ||
    enrollmentId === '' ||
    typeof environmentInstanceId !== 'string' ||
    environmentInstanceId === '' ||
    typeof protocolVersion !== 'string' ||
    typeof host !== 'string' ||
    host === '' ||
    typeof port !== 'number' ||
    !Number.isInteger(port) ||
    port < 1 ||
    port > 65_535 ||
    typeof identityFileName !== 'string' ||
    identityFileName !== WORKER_IDENTITY_FILE
  ) {
    throw new WorkerHostStateError('invalid', 'the host-local Worker configuration is incomplete');
  }
  return {
    version: 1,
    enrollmentId,
    environmentInstanceId,
    protocolVersion,
    endpoint: { host, port },
    identityFileName,
  };
}

/** Persist the configuration with owner-only permissions. */
export function writeConfig(paths: WorkerHostPaths, config: WorkerHostConfig): void {
  writePrivateFile(paths.configPath, `${JSON.stringify(config, null, 2)}\n`);
}

const SAFE_RUNTIME_DETAILS = new Set([
  'the Worker identity is proven and awaiting Human approval',
  WORKER_DIAGNOSTICS.protocolIncompatible,
  WORKER_DIAGNOSTICS.enrollmentRefused,
  // Retain records written by earlier E3 revisions while new records use the
  // shared product-owned diagnostic allowlist above.
  'the Worker protocol is incompatible',
  'the Worker identity or enrollment was refused',
  'the Worker connection could not be established',
  'the Sprout instance refused the connection',
]);

/** Write the live daemon's state record with owner-only, sanitized diagnostics. */
export function writeRuntimeState(paths: WorkerHostPaths, state: WorkerRuntimeState): void {
  const safeState: WorkerRuntimeState = state.detail === undefined
    ? state
    : { ...state, detail: SAFE_RUNTIME_DETAILS.has(state.detail) ? state.detail : 'the Worker connection could not be established' };
  writePrivateFile(paths.runtimePath, `${JSON.stringify(safeState, null, 2)}\n`);
}

/**
 * Read the live daemon's state record, returning `undefined` when absent.
 *
 * A record that is present but does not match the schema (an unknown state
 * string, a non-numeric pid or instant) is a *local configuration failure*,
 * not a silent absence: `status` must never project a corrupt runtime record
 * into a healthy-looking stopped state, so this throws `invalid`.
 */
export function readRuntimeState(paths: WorkerHostPaths): WorkerRuntimeState | undefined {
  if (!existsSync(paths.runtimePath)) return undefined;
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(paths.runtimePath, 'utf8')) as unknown;
  } catch {
    throw new WorkerHostStateError('invalid', 'the host-local runtime state record is not valid JSON');
  }
  if (typeof parsed !== 'object' || parsed === null) {
    throw new WorkerHostStateError('invalid', 'the host-local runtime state record is malformed');
  }
  const record = parsed as Record<string, unknown>;
  const state = record['state'];
  if (
    typeof record['pid'] !== 'number' ||
    !Number.isInteger(record['pid']) ||
    (record['pid'] as number) <= 0 ||
    typeof state !== 'string' ||
    !isConnectionState(state) ||
    typeof record['at'] !== 'number' ||
    !Number.isFinite(record['at']) ||
    !isWorkerProcessIdentity(record['process']) ||
    (record['process'] as WorkerProcessIdentity).pid !== record['pid'] ||
    (record['epoch'] !== undefined && typeof record['epoch'] !== 'number') ||
    (record['detail'] !== undefined && (typeof record['detail'] !== 'string' || !SAFE_RUNTIME_DETAILS.has(record['detail'])))
  ) {
    throw new WorkerHostStateError('invalid', 'the host-local runtime state record is malformed');
  }
  return parsed as WorkerRuntimeState;
}

function isWorkerProcessIdentity(value: unknown): value is WorkerProcessIdentity {
  if (typeof value !== 'object' || value === null) return false;
  const record = value as Record<string, unknown>;
  return (
    typeof record['pid'] === 'number' && Number.isInteger(record['pid']) && record['pid'] > 0 &&
    typeof record['startIdentity'] === 'string' && record['startIdentity'].length > 0 && record['startIdentity'].length <= 256 &&
    typeof record['ownerToken'] === 'string' && /^[A-Za-z0-9_-]{43}$/.test(record['ownerToken'])
  );
}

function isConnectionState(value: string): value is WorkerConnectionState {
  return ['stopped', 'connecting', 'connected', 'pending-approval', 'incompatible', 'revoked'].includes(value);
}

/** Remove the runtime state record. */
export function clearRuntimeState(paths: WorkerHostPaths): void {
  removeFileIfPresent(paths.runtimePath);
}

/**
 * Whether a pid names a live process.
 *
 * `EPERM` means the process exists but belongs to another user; the Worker only
 * ever cares about its own uid, so it is still treated as alive.
 */
export function isProcessAlive(pid: number): boolean {
  if (!Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    return (error as NodeJS.ErrnoException).code === 'EPERM';
  }
}

/** Generate an unguessable, non-secret local owner token for one Worker start. */
export function createWorkerOwnerToken(): string {
  return randomBytes(32).toString('base64url');
}

/** Exact equality for a PID, its OS start incarnation, and its owner token. */
export function sameWorkerProcess(
  expected: WorkerProcessIdentity,
  actual: WorkerProcessIdentity | undefined,
): boolean {
  return actual !== undefined &&
    expected.pid === actual.pid &&
    expected.startIdentity === actual.startIdentity &&
    expected.ownerToken === actual.ownerToken;
}

/**
 * Read the process identity for a Worker process.  This intentionally does not
 * inspect the command line: command words are neither ownership nor an
 * environment binding.
 *
 * Darwin exposes both the process start time and environment through `ps`; on
 * Linux the equivalent owner-only `/proc` entries are used so local tests and
 * development carriers retain the same safety property. Unsupported platforms
 * and unreadable evidence return `unknown` and therefore fail closed (never
 * trust or steal a possibly live record).
 */
export function probeWorkerProcess(pid: number): WorkerProcessProbeResult {
  if (!isProcessAlive(pid)) return { state: 'dead' };
  try {
    const ownerToken = process.platform === 'linux'
      ? environmentValue(readFileSync(`/proc/${pid}/environ`), 'SPROUT_WORKER_OWNER_TOKEN')
      : darwinEnvironmentValue(pid);
    const startIdentity = process.platform === 'linux'
      ? linuxStartIdentity(pid)
      : process.platform === 'darwin'
        ? darwinStartIdentity(pid)
        : undefined;
    if (ownerToken === undefined || startIdentity === undefined) return { state: 'unknown' };
    const identity = { pid, startIdentity, ownerToken };
    return isWorkerProcessIdentity(identity)
      ? { state: 'alive', process: identity }
      : { state: 'unknown' };
  } catch {
    return { state: 'unknown' };
  }
}

/** Bind the current process after `start` has installed its owner token. */
export function currentWorkerProcess(ownerToken: string): WorkerProcessIdentity {
  const evidence = probeWorkerProcess(process.pid);
  if (evidence.state !== 'alive' || evidence.process.ownerToken !== ownerToken) {
    throw new WorkerHostStateError('invalid', 'could not establish a host-local Worker process identity');
  }
  return evidence.process;
}

function environmentValue(contents: Buffer | string, name: string): string | undefined {
  const prefix = `${name}=`;
  for (const entry of contents.toString('utf8').split('\0')) {
    if (entry.startsWith(prefix)) {
      const value = entry.slice(prefix.length);
      return /^[A-Za-z0-9_-]{43}$/.test(value) ? value : undefined;
    }
  }
  return undefined;
}

function linuxStartIdentity(pid: number): string | undefined {
  const stat = readFileSync(`/proc/${pid}/stat`, 'utf8');
  const close = stat.lastIndexOf(')');
  if (close < 0) return undefined;
  // The tail begins at field 3; field 22 (starttime) is therefore index 19.
  const startTicks = stat.slice(close + 2).trim().split(/\s+/)[19];
  return startTicks !== undefined && /^\d+$/.test(startTicks) ? `linux:${startTicks}` : undefined;
}

function darwinStartIdentity(pid: number): string | undefined {
  const output = execFileSync('ps', ['-p', String(pid), '-o', 'lstart='], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  return output === '' ? undefined : `darwin:${output}`;
}

function darwinEnvironmentValue(pid: number): string | undefined {
  // `-E` asks ps for the process environment. We extract only the exact opaque
  // variable; no command text or unrelated environment values are retained.
  const output = execFileSync('ps', ['-wwE', '-p', String(pid), '-o', 'command='], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
  const match = output.match(/(?:^|\s)SPROUT_WORKER_OWNER_TOKEN=([A-Za-z0-9_-]{43})(?=\s|$)/);
  return match?.[1];
}

/** Run one host command and return its stdout, throwing on a non-zero exit. */
export type CommandRunner = (command: string, args: readonly string[]) => string;

/**
 * Read a one-use claim secret from stdin without echoing it.
 *
 * The secret never becomes an argument and never enters shell history. On a TTY
 * the terminal echo is disabled for the duration and nothing is written back; on
 * a pipe the line is read directly. The value is bounded, so a stream that never
 * terminates cannot exhaust memory, and it is never written to the log.
 */
export async function readSecretFromStdin(
  input: NodeJS.ReadableStream & { isTTY?: boolean; setRawMode?: (mode: boolean) => void },
  output: NodeJS.WritableStream,
  prompt: string,
): Promise<string> {
  output.write(prompt);
  if (input.isTTY === true && typeof input.setRawMode === 'function') {
    return readSecretRaw(input, output);
  }
  return readSecretLine(input);
}

const MAX_SECRET_LENGTH = 4_096;

function readSecretRaw(
  input: NodeJS.ReadableStream & { setRawMode?: (mode: boolean) => void },
  output: NodeJS.WritableStream,
): Promise<string> {
  return new Promise((resolve, reject) => {
    let secret = '';
    input.setRawMode?.(true);
    input.resume();
    const finish = (error?: Error): void => {
      input.setRawMode?.(false);
      input.removeListener('data', onData);
      output.write('\n');
      if (error !== undefined) reject(error);
      else resolve(secret);
    };
    const onData = (chunk: Buffer | string): void => {
      for (const character of chunk.toString('utf8')) {
        if (character === '\n' || character === '\r') {
          finish();
          return;
        }
        if (character === '\u0003') {
          finish(new Error('enrollment cancelled'));
          return;
        }
        if (character === '\u007f' || character === '\b') {
          secret = secret.slice(0, -1);
          continue;
        }
        if (secret.length >= MAX_SECRET_LENGTH) continue;
        secret += character;
      }
    };
    input.on('data', onData);
    input.on('error', (error) => finish(error instanceof Error ? error : new Error(String(error))));
  });
}

function readSecretLine(input: NodeJS.ReadableStream): Promise<string> {
  return new Promise((resolve, reject) => {
    let buffer = '';
    const onData = (chunk: Buffer | string): void => {
      buffer += chunk.toString('utf8');
      const newline = buffer.search(/[\r\n]/);
      if (newline === -1) {
        if (buffer.length > MAX_SECRET_LENGTH) {
          cleanup();
          reject(new Error('the enrollment claim secret is unreasonably long'));
        }
        return;
      }
      const secret = buffer.slice(0, newline);
      cleanup();
      resolve(secret);
    };
    const onEnd = (): void => {
      cleanup();
      resolve(buffer.trim());
    };
    const onError = (error: Error): void => {
      cleanup();
      reject(error);
    };
    const cleanup = (): void => {
      input.removeListener('data', onData);
      input.removeListener('end', onEnd);
      input.removeListener('error', onError);
    };
    input.on('data', onData);
    input.on('end', onEnd);
    input.on('error', onError);
  });
}

/**
 * A host-local single-instance lock.
 *
 * Two Workers for the same environment must never both run: the core would see
 * two identities competing for one epoch, and a duplicate connection could
 * invalidate a healthy one. The lock is an owner-only process binding: a pid,
 * opaque owner token, and OS start identity. A pid or command line is never
 * sufficient evidence of ownership.
 */
export class DuplicateWorkerProcessError extends Error {
  override readonly name = 'DuplicateWorkerProcessError';
  /** The pid of the live holder, when the lock file named one legibly. */
  readonly pid: number | undefined;

  constructor(pid?: number) {
    super(
      pid === undefined
        ? 'another Sprout Worker for this environment is already running'
        : `another Sprout Worker for this environment is already running (pid ${pid})`,
    );
    this.pid = pid;
  }
}

/** The owner-only lock directory a running Worker holds for the lifetime of `start`. */
export function workerLockPath(paths: WorkerHostPaths): string {
  return join(paths.stateDirectory, 'worker.lock');
}

type WorkerLockKind = 'worker' | 'reset';

interface WorkerLockRecord {
  readonly version: 1;
  readonly kind: WorkerLockKind;
  readonly process: WorkerProcessIdentity;
}

/** Test-only observation point for the release/replacement interleaving. */
export interface WorkerLockOptions {
  /** Called after a release has observed the pathname, before its atomic take. */
  readonly onReleaseObserved?: () => void;
  /** Test-only crash point after each ownership transition reaches the filesystem. */
  readonly onTransition?: (transition: WorkerLockTransition) => void;
}

/** Durable lock transitions used by the crash-at-each-transition tests. */
export type WorkerLockTransition =
  | 'pending-stage-created'
  | 'pending-stage-synced'
  | 'pending-published'
  | 'canonical-created'
  | 'owner-published'
  | 'owner-retired'
  | 'canonical-removed'
  | 'release-complete';

type WorkerLockClassification = 'duplicate' | 'stale' | 'unknown';

/** The private, token-bound entry held inside the canonical lock directory. */
function workerLockOwnerName(processIdentity: WorkerProcessIdentity): string {
  return `owner-${processIdentity.ownerToken}`;
}

function workerLockOwnerPath(lockPath: string, processIdentity: WorkerProcessIdentity): string {
  return join(lockPath, workerLockOwnerName(processIdentity));
}

/**
 * Classify the current lock file from the caller's point of view.
 *
 * - `duplicate`: an exact live process binding holds it; refuse.
 * - `stale`: the owner pid is positively known dead, or an observed live
 *   process has a different complete binding; reclaim is safe.
 * - `unknown`: the lock is malformed or the process evidence is unavailable;
 *   refuse rather than steal a possibly live Worker or reset fence.
 */
function classifyLock(lockPath: string, probe: WorkerProcessProbe): WorkerLockClassification {
  const holder = readWorkerLock(lockPath);
  if (holder === undefined) return 'unknown';
  const evidence = probe(holder.process.pid);
  if (evidence.state === 'dead') return 'stale';
  if (evidence.state === 'unknown') return 'unknown';
  return sameWorkerProcess(holder.process, evidence.process) ? 'duplicate' : 'stale';
}

/** A durable lifecycle marker outside the canonical lock directory. */
function lifecyclePath(lockPath: string, phase: 'pending' | 'releasing', processIdentity: WorkerProcessIdentity): string {
  return `${lockPath}.${phase}-${processIdentity.ownerToken}-${randomBytes(8).toString('hex')}`;
}

function lifecycleEntries(lockPath: string): string[] {
  const parent = dirname(lockPath);
  const lockName = escapeRegularExpression(basename(lockPath));
  // The suffix-free pending shape is retained only so a complete marker from
  // the previous protocol revision remains recoverable after upgrade. New
  // markers always carry a nonce; `.preparing` records are intentionally not
  // lifecycle evidence and are handled separately below.
  const lifecycleName = new RegExp(
    `^${lockName}\\.(?:pending-[A-Za-z0-9_-]{43}(?:-[0-9a-f]{16})?|releasing-[A-Za-z0-9_-]{43}-[0-9a-f]{16})$`,
  );
  try {
    return readdirSync(parent)
      .filter((entry) => lifecycleName.test(entry))
      .map((entry) => join(parent, entry));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw error;
  }
}

function escapeRegularExpression(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Flush one directory entry update before calling the transition durable. */
function syncDirectory(directory: string): void {
  const descriptor = openSync(directory, 'r');
  try {
    fsyncSync(descriptor);
  } finally {
    closeSync(descriptor);
  }
}

/**
 * Discard records that were never atomically published as ownership evidence.
 *
 * A `.preparing` file is a staging inode by grammar, not a lock claim. It may
 * contain zero bytes, a truncated JSON prefix, or a complete record if the
 * process died immediately before rename. None acquired the canonical lock,
 * so removing it cannot steal a Worker or reset fence. Published pending,
 * releasing, and canonical owner records remain subject to process evidence
 * and continue to fail closed when that evidence is unknown.
 */
function recoverIncompleteLockTransitions(lockPath: string): void {
  const parent = dirname(lockPath);
  const lockName = escapeRegularExpression(basename(lockPath));
  const preparingName = new RegExp(
    `^${lockName}\\.pending-[A-Za-z0-9_-]{43}-[0-9a-f]{16}\\.preparing$`,
  );
  let entries: string[];
  try {
    entries = readdirSync(parent);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
    throw error;
  }
  for (const entry of entries) {
    if (!preparingName.test(entry)) continue;
    const staged = join(parent, entry);
    try {
      if (lstatSync(staged).isFile()) unlinkSync(staged);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        // A preparation has no authority and therefore must not wedge start or
        // reset merely because unrelated cleanup failed. It remains ignored by
        // lifecycle parsing and can be removed by later host maintenance.
      }
    }
  }
}

/** Publish one complete pending record; the final name can never be truncated. */
function publishPendingLock(
  lockPath: string,
  kind: WorkerLockKind,
  processIdentity: WorkerProcessIdentity,
  options: WorkerLockOptions,
): string {
  const pendingPath = lifecyclePath(lockPath, 'pending', processIdentity);
  const stagedPath = `${pendingPath}.preparing`;
  let descriptor: number | undefined;
  let published = false;
  try {
    descriptor = openSync(stagedPath, 'wx', PRIVATE_FILE_MODE);
    options.onTransition?.('pending-stage-created');
    writeFileSync(
      descriptor,
      `${JSON.stringify({ version: 1, kind, process: processIdentity } satisfies WorkerLockRecord)}\n`,
      'utf8',
    );
    fsyncSync(descriptor);
    closeSync(descriptor);
    descriptor = undefined;
    options.onTransition?.('pending-stage-synced');
    renameSync(stagedPath, pendingPath);
    published = true;
    syncDirectory(dirname(lockPath));
    options.onTransition?.('pending-published');
    return pendingPath;
  } catch (error) {
    if (descriptor !== undefined) {
      try { closeSync(descriptor); } catch { /* preserve the publication error */ }
    }
    if (!published) {
      try { unlinkSync(stagedPath); } catch { /* crash recovery ignores unpublished staging */ }
    }
    throw error;
  }
}

function readLockRecordFile(filePath: string): WorkerLockRecord | undefined {
  try {
    const parsed: unknown = JSON.parse(readFileSync(filePath, 'utf8'));
    if (typeof parsed !== 'object' || parsed === null) return undefined;
    const record = parsed as Record<string, unknown>;
    if (record['version'] !== 1 || (record['kind'] !== 'worker' && record['kind'] !== 'reset') || !isWorkerProcessIdentity(record['process'])) return undefined;
    return record as unknown as WorkerLockRecord;
  } catch {
    return undefined;
  }
}

/**
 * Recognize the pre-atomic pending name written by the immediately preceding
 * E3 revision. Only that suffix-free pending phase may be classified as an
 * interrupted publication when its record is truncated. New nonce-bearing
 * pending markers are atomically complete, so malformed content there (or in
 * any owner/releasing record) remains unknown evidence and is never reclaimed.
 */
function isLegacyPendingPath(lockPath: string, marker: string): boolean {
  const lockName = escapeRegularExpression(basename(lockPath));
  return new RegExp(`^${lockName}\\.pending-[A-Za-z0-9_-]{43}$`).test(basename(marker));
}

function recoverLegacyIncompletePending(lockPath: string, marker: string): WorkerLockClassification | undefined {
  if (!isLegacyPendingPath(lockPath, marker)) return 'unknown';
  if (existsSync(lockPath)) {
    try {
      if (readdirSync(lockPath).length !== 0) {
        // The malformed legacy pending record never became ownership evidence;
        // leave the complete canonical owner to ordinary classification.
        unlinkSync(marker);
        return undefined;
      }
      rmdirSync(lockPath);
    } catch {
      return 'unknown';
    }
  }
  try {
    unlinkSync(marker);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') return 'unknown';
  }
  return 'stale';
}

/**
 * Recover a lifecycle marker without treating missing process evidence as death.
 * The canonical directory is removed before its marker, so a crash cannot leave
 * an empty canonical lock with no durable recovery evidence.
 */
function recoverLockLifecycle(lockPath: string, probe: WorkerProcessProbe): WorkerLockClassification | undefined {
  const markers = lifecycleEntries(lockPath);
  if (markers.length === 0) return undefined;
  if (markers.length !== 1) return 'unknown';
  const marker = markers[0];
  if (marker === undefined) return 'unknown';
  const record = readLockRecordFile(marker);
  if (record === undefined) return recoverLegacyIncompletePending(lockPath, marker);
  // Releasing markers still carry process evidence: an interrupted cleanup
  // must not turn an unreadable owner into automatic reclaim, even if the
  // canonical directory was already removed.
  const evidence = probe(record.process.pid);
  if (evidence.state === 'unknown') return 'unknown';
  if (evidence.state === 'alive' && sameWorkerProcess(record.process, evidence.process)) return 'duplicate';
  // A stale pending marker can be removed even when another valid owner now
  // occupies the canonical directory: it never acquired authority. A
  // releasing marker with a non-empty canonical directory is external or
  // concurrent mutation and remains fail-closed.
  if (existsSync(lockPath)) {
    try {
      if (readdirSync(lockPath).length !== 0) {
        if (marker.includes(`${lockPath}.pending-`)) {
          unlinkSync(marker);
          return undefined;
        }
        return 'unknown';
      }
      rmdirSync(lockPath);
    } catch {
      return 'unknown';
    }
  }
  try {
    unlinkSync(marker);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') return 'unknown';
  }
  return 'stale';
}

/** Move one exact owner entry to a durable, owner-token-bound release marker. */
function retireWorkerLock(lockPath: string, processIdentity: WorkerProcessIdentity): string | undefined {
  const marker = lifecyclePath(lockPath, 'releasing', processIdentity);
  try {
    renameSync(workerLockOwnerPath(lockPath, processIdentity), marker);
    syncDirectory(lockPath);
    syncDirectory(dirname(lockPath));
    return marker;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
    throw error;
  }
}

/** Reclaim a stale lock while preserving a recoverable crash marker. */
function reclaimStaleWorkerLock(lockPath: string, probe: WorkerProcessProbe): WorkerLockClassification {
  const holder = readWorkerLock(lockPath);
  if (holder === undefined) return recoverLockLifecycle(lockPath, probe) ?? 'unknown';
  const classification = classifyLock(lockPath, probe);
  if (classification !== 'stale') return classification;
  const marker = retireWorkerLock(lockPath, holder.process);
  if (marker === undefined) return classifyLock(lockPath, probe);
  try {
    rmdirSync(lockPath);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      try { unlinkSync(marker); } catch { /* canonical absence is already proven */ }
      return 'stale';
    }
    if ((error as NodeJS.ErrnoException).code === 'ENOTEMPTY') return classifyLock(lockPath, probe);
    throw error;
  }
  try { unlinkSync(marker); } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
  return 'stale';
}

/** Release is bound to the exact owner entry and leaves a durable marker. */
function releaseWorkerLock(
  lockPath: string,
  processIdentity: WorkerProcessIdentity,
  options: WorkerLockOptions,
): void {
  if (options.onReleaseObserved !== undefined) {
    void readWorkerLock(lockPath);
    options.onReleaseObserved();
  }
  const marker = retireWorkerLock(lockPath, processIdentity);
  if (marker === undefined) return;
  options.onTransition?.('owner-retired');
  try {
    rmdirSync(lockPath);
  } catch (error) {
    // A replacement can only exist after this rmdir. ENOTEMPTY/ENOENT means
    // another actor or external mutation won; never remove its lock by pathname.
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT' && (error as NodeJS.ErrnoException).code !== 'ENOTEMPTY') throw error;
    return;
  }
  syncDirectory(dirname(lockPath));
  options.onTransition?.('canonical-removed');
  try { unlinkSync(marker); } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
  syncDirectory(dirname(lockPath));
  options.onTransition?.('release-complete');
}

/**
 * Acquire the single-instance lock, or throw when a live Worker holds it.
 *
 * The check-then-write race is closed by creating the lock directory
 * exclusively (`mkdir`):
 * two concurrent `start` processes can never both acquire it, and the loser of
 * an `EEXIST` re-reads the winner's binding and fails with the documented
 * duplicate-process error rather than a generic filesystem failure. A normal
 * lock is reclaimed only when its owner is proven dead or replaced; unavailable
 * process evidence is a duplicate-process refusal, including for reset fences.
 */
export function acquireWorkerLock(
  paths: WorkerHostPaths,
  processIdentity: WorkerProcessIdentity,
  probe: WorkerProcessProbe = probeWorkerProcess,
  kind: WorkerLockKind = 'worker',
  options: WorkerLockOptions = {},
): { readonly release: () => void; readonly path: string } {
  if (!isWorkerProcessIdentity(processIdentity)) {
    throw new WorkerHostStateError('invalid', 'could not establish a valid host-local Worker process identity');
  }
  ensureStateDirectory(paths);
  const lockPath = workerLockPath(paths);
  for (let attempt = 0; attempt < 4; attempt += 1) {
    const lifecycle = recoverLockLifecycle(lockPath, probe);
    if (lifecycle === 'unknown' || lifecycle === 'duplicate') {
      throw new DuplicateWorkerProcessError(readWorkerLock(lockPath)?.process.pid);
    }
    let pendingPath: string;
    try {
      pendingPath = publishPendingLock(lockPath, kind, processIdentity, options);
    } catch (error) {
      // Another contender may have safely discarded our unpublished staging
      // record before publication. Retry the protocol rather than surfacing a
      // generic filesystem failure; exclusive canonical mkdir still chooses
      // the only owner.
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue;
      throw error;
    }
    try {
      mkdirSync(lockPath, { mode: PRIVATE_DIRECTORY_MODE });
    } catch (error) {
      try { unlinkSync(pendingPath); } catch { /* recovery marker remains only on an interrupted process */ }
      if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
      const classification = classifyLock(lockPath, probe);
      if (classification !== 'stale') {
        throw new DuplicateWorkerProcessError(readWorkerLock(lockPath)?.process.pid);
      }
      const reclaimed = reclaimStaleWorkerLock(lockPath, probe);
      if (reclaimed !== 'stale') {
        throw new DuplicateWorkerProcessError(readWorkerLock(lockPath)?.process.pid);
      }
      continue;
    }
    // Once mkdir succeeds, the complete pending marker must remain until it is
    // renamed into the owner entry. A later fsync/hook failure therefore leaves
    // recoverable evidence instead of an empty, permanently wedged directory.
    syncDirectory(dirname(lockPath));
    options.onTransition?.('canonical-created');
    const ownerPath = workerLockOwnerPath(lockPath, processIdentity);
    try {
      // The pending marker is prepared before mkdir. Renaming it into the
      // canonical directory makes an interrupted start recoverable instead of
      // wedging an empty lock directory forever.
      renameSync(pendingPath, ownerPath);
      syncDirectory(dirname(lockPath));
      syncDirectory(lockPath);
      options.onTransition?.('owner-published');
    } catch (error) {
      try { rmdirSync(lockPath); } catch { /* preserve the original failure */ }
      throw error;
    }
    recoverIncompleteLockTransitions(lockPath);
    return {
      path: lockPath,
      release: () => releaseWorkerLock(lockPath, processIdentity, options),
    };
  }
  // The second exclusive create also lost: a concurrent starter won it.
  throw new DuplicateWorkerProcessError(readWorkerLock(lockPath)?.process.pid);
}

function readWorkerLock(lockPath: string): WorkerLockRecord | undefined {
  try {
    const entries = readdirSync(lockPath);
    const ownerEntries = entries.filter((entry) => /^owner-[A-Za-z0-9_-]{43}$/.test(entry));
    if (ownerEntries.length !== 1) return undefined;
    const ownerEntry = ownerEntries[0];
    if (ownerEntry === undefined) return undefined;
    const parsed: unknown = JSON.parse(readFileSync(join(lockPath, ownerEntry), 'utf8'));
    if (typeof parsed !== 'object' || parsed === null) return undefined;
    const record = parsed as Record<string, unknown>;
    if (record['version'] !== 1 || (record['kind'] !== 'worker' && record['kind'] !== 'reset') || !isWorkerProcessIdentity(record['process'])) return undefined;
    const lock = record as unknown as WorkerLockRecord;
    return ownerEntry === workerLockOwnerName(lock.process) ? lock : undefined;
  } catch {
    return undefined;
  }
}

/**
 * The pid of the live Worker daemon that currently holds the lock, if any.
 *
 * `reset` refuses while this returns a pid: removing the identity under a
 * running foreground Worker would leave a process holding a key the operator
 * believes is gone.
 */
export function activeWorkerLockHolder(
  paths: WorkerHostPaths,
  probe: WorkerProcessProbe = probeWorkerProcess,
): number | undefined {
  const lock = readWorkerLock(workerLockPath(paths));
  const evidence = lock === undefined ? undefined : probe(lock.process.pid);
  if (lock?.kind === 'worker' && evidence?.state === 'alive' && sameWorkerProcess(lock.process, evidence.process)) {
    return lock.process.pid;
  }
  return undefined;
}

/** Acquire the exclusive maintenance fence used by reset. */
export function acquireWorkerResetLock(
  paths: WorkerHostPaths,
  processIdentity: WorkerProcessIdentity,
  probe: WorkerProcessProbe = probeWorkerProcess,
): { readonly release: () => void; readonly path: string } {
  return acquireWorkerLock(paths, processIdentity, probe, 'reset');
}

/**
 * Remove every host-local Worker file, used by `reset`.
 *
 * Removal is fail-closed: an unlink error other than an already-absent file
 * propagates, so `reset` can never report success while the old identity key
 * or configuration is still on disk.
 */
export function removeHostState(paths: WorkerHostPaths, options: { readonly preserveLock?: boolean } = {}): void {
  const files = [paths.identityPath, paths.configPath, paths.runtimePath, ...(options.preserveLock ? [] : [workerLockPath(paths)])];
  // Validate all entries before the first unlink. This catches corrupted state
  // such as a directory at a record path without leaving earlier records gone.
  const snapshot = files.flatMap((filePath) => {
    try {
      const stat = lstatSync(filePath);
      if (!stat.isFile()) {
        throw new WorkerHostStateError('invalid', 'the host-local Worker state contains an unsafe non-file entry');
      }
      return [{ filePath, content: readFileSync(filePath), mode: stat.mode & 0o777 }];
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return [];
      throw error;
    }
  });
  const removed: typeof snapshot = [];
  try {
    for (const record of snapshot) {
      removeFileRequired(record.filePath);
      removed.push(record);
    }
  } catch (error) {
    // Restore every successfully unlinked record before reporting failure. The
    // files are private state owned by this command, so this is a bounded local
    // transaction rather than a best-effort cleanup.
    for (const record of removed) {
      try {
        writeFileSync(record.filePath, record.content, { mode: record.mode });
        chmodSync(record.filePath, record.mode);
      } catch {
        // Preserve the original destructive error; a later recovery can still
        // see a failed reset rather than a false success.
      }
    }
    throw error;
  }
  // The directory is removed only when it is empty, so an operator's unrelated
  // files under an overridden state root are never deleted by `reset`.
  try {
    rmdirSync(paths.stateDirectory);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT' && (error as NodeJS.ErrnoException).code !== 'ENOTEMPTY') {
      throw error;
    }
  }
}
